server:
  port: 7070
spring:
  application:
    name: MeiTuan_backend
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/meituan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: 11111
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.meituan.model

minio:
  endpoint: http://10.100.15.60:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: meituan

#  启动minio命令： ./minio.exe server D:\LenovoSoftstore\store